### ISSUE TITLE
CREATE TABLE

### ISSUE THREAD

**Issue by BaharF** [hpcc-systems/HSQL#75]

**Comment by BaharF** [comment]
Currently HSQL supports LAYOUT command which is not a SQL command: 
https://github.com/hpcc-systems/HSQL/blob/master/hsqlt/notes/syntax.md#layout

Layout allows to create a layout structure for functions and for loading up datasets as tables.

Syntax
x = layout (
  <datatype1> <col1>,
  <datatype2> <col2>,...
);

Instead we need CREATE TABLE which is a support SQL command: https://www.w3schools.com/sql/sql_create_table.asp
CREATE TABLE table_name (
    column1 datatype,
    column2 datatype,
    column3 datatype,
   ....
);

Please add CREATE TABLE, and remove LAYOUT syntax.

**Comment by m-kashani** [comment]
- [ ] Research about the differences:
https://hpccsystems.com/training/documentation/ecl-language-reference/html/DATASET.html
https://hpccsystems.com/training/documentation/ecl-language-reference/html/TABLE.html

**Comment by BaharF** [comment]
This is creating RECORD for the DATASET, if this is any of help.

**Comment by m-kashani** [comment]
- [ ] Making an example for .HSQL -> .ecl desired result.
- [ ] Figuring out and setting up the debugger.
- [ ] Creating the Parse Tree for the Layout.hsql.
- [ ] Call graph to show what layout is related to.
- [ ] Preparing a list of related commits.

**Comment by m-kashani** [comment]
- [ ] Preparing a list of related commits.

Date | Commits |   |   | File changes ! |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
16 Jul | [layout] add layout grammar |   |   | 4 | HSQL.g4 | HSQL.interp | HSQLParser.ts | HSQLVisitor.ts |  
16 Jul | [layout] generation |   |   | 1 | DeclarationGeneration.ts |   |   |   |  
17 Jul | [layout] add create layout |   |   | 13 | HSQL.g4 | input.hsql | IASTVisitor.ts | Singular.ts |  
18 Jul | [layout] select from dataset grammar |   |   | 7 | HSQL.g4 | ASTVisitor.ts | /CreateLayout.ts | /ECLGenerator.ts |

**Comment by m-kashani** [comment]
There are two changes that we need to make:

- [ ] 1) Create a new syntax for this and test it.

https://github.com/hpcc-systems/HSQL/commit/25136949d3030660069ff667d6decf2f4d2ffb26#commitcomment-57390742

- [ ] 2) Generate the same Abstract Syntax Tree. ( As we don't need to change the code generator step ).

**Comment by m-kashani** [comment]
For the first step :

- [x] I wrote a new syntax for 1- `createStmt` & 2-`createTableStmt` ( in our  grammar.g4).

The `createStmt` works as you requested:
```
foo = CREATE TABLE ( 
    column1 datatype,
    column2 datatype
); 
```

The `createTableStmt` should be working as it was requested initially ( EXACT SQL syntax ) and I kept it in our code for ease of new users.
```
CREATE TABLE table_name{
    A1 INTEGER,
    A2 STRING
}
```
These two syntaxes are using the `fieldContent` instead of `layoutContent`, so the:

`fieldContent` uses a new column definition (newcolDefs) :
![image](https://user-images.githubusercontent.com/3967516/137500339-1a19db11-2344-45cd-9f75-ef353c521ebc.png)

while our old `layoutContent` is still working:
![image](https://user-images.githubusercontent.com/3967516/137500456-4ba1d6e9-8930-4a06-bcf4-bf5774ee8d9e.png)

In addition to our previous exact SQL syntax.

- [x] I did refactor the newcolDefs name and its grammar and edited the ColDefASTGenerator.ts and its methods. Then I updated the src/misc/grammar file generated by antlr4.ts. Then I updated our ASTGenerator.ts (ASTGenerator.visitCreateStmt() & ASTGenerator.visitCreateTableStmt). These two methods are being used inside our two new syntaxes.

Once the parse tree is generated it should be handed to the ASTgenerator. 
I reordered the AST.ts imported files ( as they are being called).

Reordered the imported files as they are being used in the program (up to this request) and added some documentation for `ASTGenerator.ts`, as much as possible.

- [ ] (It's not fully commented yet)

Wrote two new methods for visitCreateTable and visitCreate inside the `IASTVisitor.ts` interface. ( visitCreateTable ). + Comment.
Reordered the classes as they are being called.
- [ ] We have to separate the ErrorManagerContainer & ASTGen later.

![image](https://user-images.githubusercontent.com/3967516/137521512-c3e76ac5-d689-4c69-908f-49ac9e913ea7.png)

- [x] Cleaned out the `CreateLayout.ts` and created two new classes separated from each other. ( `CreateTable.ts` and `Create.ts`) and introduced them inside the `ECLGenerator.ts`

- [x] Tested the sample input.hsql and input.ecl with the CLI tool as follow:

![image](https://user-images.githubusercontent.com/3967516/137496607-678e6d5b-ef08-4421-9908-e7341fed24ea.png)

Updated the extension, possible security bot issues.

![image](https://user-images.githubusercontent.com/3967516/137526609-9160aa18-a7cb-4114-9f82-86337880845f.png)

@dcamper @BaharF 
You can install the createTable.vis extension to test the generated code using (Shift+Ctrl+P) and compile it into desired .ecl and ready for the code review.

https://github.com/hpcc-systems/HSQL/commit/7ccbb3a76ba1243796f66d4b52c9a62c355b022e
